defaults:
  - default
  - _self_

# checkpoint
checkpoint_path:
save_path: 'logs/'
dataset_path: '../bedrock_dataset'

# env
env_name: aws_env
env_load_path: ''
seed: 6
port_number: 1000
num_envs: 4 # this is not used during SFT.
num_eval_envs: 32 # number of parallel environments used for evaluation
log_every: 1 # logging frequency
max_conversation_length: 10 # Conversation length after which the account state is reset.
env_type: easy #  Environment type: [easy, medium, hard]

# training hyperparameters
rollout_size: 128 # number of rollout trajectories for each update: This parameter is not used during SFT
batch_size: 2
iterations: 200 # total number of iterations
epochs: 50 # number of epochs for the critic each iteration: This parameter is not used during SFT.
actor_epochs: 3 # number of actor updates per iteration
grad_accum_steps: 32 # Gradient accumulation steps --> Effective batch size is grad_accum_steps x batch_size
lm_lr: 5e-5 # Learning rate for the LLM
eval_temperature: 0.1 # Temperature used for sampling during evaluation

# wandb logging
use_wandb: True
project_name: 'aws_env'
run_name: 'archer-acc'